<?php
$title = 'Booking Calendar';
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h1 class="h3 mb-0">Booking Calendar</h1>
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#addAvailabilityModal">
                        <i class="fas fa-plus"></i> Add Availability
                    </button>
                    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#bulkUpdateModal">
                        <i class="fas fa-edit"></i> Bulk Update
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Calendar Controls -->
        <div class="col-12 mb-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-md-4">
                            <div class="d-flex align-items-center">
                                <button class="btn btn-outline-secondary me-2" id="prevMonth">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <h4 class="mb-0 me-2" id="currentMonth"><?= date('F Y') ?></h4>
                                <button class="btn btn-outline-secondary" id="nextMonth">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <select class="form-select" id="hotelFilter">
                                    <option value="">All Hotels</option>
                                    <?php if (isset($hotels) && !empty($hotels)): ?>
                                        <?php foreach ($hotels as $hotel): ?>
                                            <option value="<?= $hotel['id'] ?>"><?= htmlspecialchars($hotel['name']) ?></option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <select class="form-select" id="roomFilter">
                                    <option value="">All Rooms</option>
                                    <?php if (isset($rooms) && !empty($rooms)): ?>
                                        <?php foreach ($rooms as $room): ?>
                                            <option value="<?= $room['id'] ?>" data-hotel="<?= $room['hotel_id'] ?>">
                                                <?= htmlspecialchars($room['room_type']) ?> - <?= htmlspecialchars($room['hotel_name']) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Calendar View -->
        <div class="col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h5 class="card-title mb-0">
                        <i class="fas fa-calendar-alt"></i> Monthly View
                    </h5>
                </div>
                <div class="card-body p-0">
                    <div id="calendar" class="calendar-container">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </div>

        <!-- Sidebar -->
        <div class="col-lg-4">
            <!-- Legend -->
            <div class="card shadow-sm mb-4">
                <div class="card-header bg-info text-white">
                    <h6 class="card-title mb-0">
                        <i class="fas fa-info-circle"></i> Legend
                    </h6>
                </div>
                <div class="card-body">
                    <div class="legend-item d-flex align-items-center mb-2">
                        <div class="legend-color bg-success me-2" style="width: 20px; height: 20px; border-radius: 3px;"></div>
                        <span>Available</span>
                    </div>
                    <div class="legend-item d-flex align-items-center mb-2">
                        <div class="legend-color bg-warning me-2" style="width: 20px; height: 20px; border-radius: 3px;"></div>
                        <span>Partially Booked</span>
                    </div>
                    <div class="legend-item d-flex align-items-center mb-2">
                        <div class="legend-color bg-danger me-2" style="width: 20px; height: 20px; border-radius: 3px;"></div>
                        <span>Fully Booked</span>
                    </div>
                    <div class="legend-item d-flex align-items-center mb-2">
                        <div class="legend-color bg-secondary me-2" style="width: 20px; height: 20px; border-radius: 3px;"></div>
                        <span>Blocked</span>
                    </div>
                    <div class="legend-item d-flex align-items-center">
                        <div class="legend-color bg-primary me-2" style="width: 20px; height: 20px; border-radius: 3px;"></div>
                        <span>Maintenance</span>
                    </div>
                </div>
            </div>

            <!-- Today's Bookings -->
            <div class="card shadow-sm mb-4">
                <div class="card-header bg-success text-white">
                    <h6 class="card-title mb-0">
                        <i class="fas fa-calendar-day"></i> Today's Bookings
                    </h6>
                </div>
                <div class="card-body">
                    <div class="today-bookings">
                        <?php if (isset($today_bookings) && !empty($today_bookings)): ?>
                            <?php foreach ($today_bookings as $booking): ?>
                                <div class="booking-item border-bottom pb-2 mb-2">
                                    <div class="d-flex justify-content-between align-items-start">
                                        <div>
                                            <h6 class="mb-1"><?= htmlspecialchars($booking['hotel_name']) ?></h6>
                                            <p class="mb-1 small text-muted"><?= htmlspecialchars($booking['room_type']) ?></p>
                                            <p class="mb-0 small">
                                                <strong>Guest:</strong> <?= htmlspecialchars($booking['tourist_name']) ?>
                                            </p>
                                        </div>
                                        <span class="badge bg-<?= $booking['status'] === 'approved' ? 'success' : 'warning' ?>">
                                            <?= ucfirst($booking['status']) ?>
                                        </span>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <p class="text-muted text-center">No bookings for today</p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <!-- Quick Stats -->
            <div class="card shadow-sm">
                <div class="card-header bg-warning text-dark">
                    <h6 class="card-title mb-0">
                        <i class="fas fa-chart-pie"></i> This Month
                    </h6>
                </div>
                <div class="card-body">
                    <div class="row text-center">
                        <div class="col-6 mb-3">
                            <div class="stat-item">
                                <h4 class="text-success mb-1"><?= $month_stats['total_bookings'] ?? 0 ?></h4>
                                <small class="text-muted">Bookings</small>
                            </div>
                        </div>
                        <div class="col-6 mb-3">
                            <div class="stat-item">
                                <h4 class="text-primary mb-1"><?= $month_stats['occupancy_rate'] ?? 0 ?>%</h4>
                                <small class="text-muted">Occupancy</small>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="stat-item">
                                <h4 class="text-warning mb-1"><?= $month_stats['pending_bookings'] ?? 0 ?></h4>
                                <small class="text-muted">Pending</small>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="stat-item">
                                <h4 class="text-info mb-1">UGX <?= number_format($month_stats['revenue'] ?? 0) ?></h4>
                                <small class="text-muted">Revenue</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Add Availability Modal -->
<div class="modal fade" id="addAvailabilityModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Availability</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form action="/host/calendar/add-availability" method="POST" id="addAvailabilityForm">
                <div class="modal-body">
                    <input type="hidden" name="csrf_token" value="<?= View::csrfToken() ?>">
                    
                    <div class="mb-3">
                        <label for="hotel_id" class="form-label">Hotel *</label>
                        <select class="form-select" id="hotel_id" name="hotel_id" required>
                            <option value="">Select Hotel</option>
                            <?php if (isset($hotels) && !empty($hotels)): ?>
                                <?php foreach ($hotels as $hotel): ?>
                                    <option value="<?= $hotel['id'] ?>"><?= htmlspecialchars($hotel['name']) ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                    
                    <div class="mb-3">
                        <label for="room_id" class="form-label">Room</label>
                        <select class="form-select" id="room_id" name="room_id">
                            <option value="">All Rooms</option>
                        </select>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="start_date" class="form-label">Start Date *</label>
                                <input type="date" class="form-control" id="start_date" name="start_date" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="end_date" class="form-label">End Date *</label>
                                <input type="date" class="form-control" id="end_date" name="end_date" required>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-3">
                        <label for="availability_type" class="form-label">Type *</label>
                        <select class="form-select" id="availability_type" name="availability_type" required>
                            <option value="available">Available</option>
                            <option value="blocked">Blocked</option>
                            <option value="maintenance">Maintenance</option>
                        </select>
                    </div>
                    
                    <div class="mb-3">
                        <label for="price_override" class="form-label">Price Override (UGX)</label>
                        <input type="number" class="form-control" id="price_override" name="price_override" min="0" step="1000">
                        <div class="form-text">Leave empty to use default room price</div>
                    </div>
                    
                    <div class="mb-3">
                        <label for="notes" class="form-label">Notes</label>
                        <textarea class="form-control" id="notes" name="notes" rows="3"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Add Availability</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Bulk Update Modal -->
<div class="modal fade" id="bulkUpdateModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Bulk Update Availability</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form action="/host/calendar/bulk-update" method="POST" id="bulkUpdateForm">
                <div class="modal-body">
                    <input type="hidden" name="csrf_token" value="<?= View::csrfToken() ?>">
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="bulk_hotel_id" class="form-label">Hotel *</label>
                                <select class="form-select" id="bulk_hotel_id" name="hotel_id" required>
                                    <option value="">Select Hotel</option>
                                    <?php if (isset($hotels) && !empty($hotels)): ?>
                                        <?php foreach ($hotels as $hotel): ?>
                                            <option value="<?= $hotel['id'] ?>"><?= htmlspecialchars($hotel['name']) ?></option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="bulk_room_id" class="form-label">Room</label>
                                <select class="form-select" id="bulk_room_id" name="room_id">
                                    <option value="">All Rooms</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="bulk_start_date" class="form-label">Start Date *</label>
                                <input type="date" class="form-control" id="bulk_start_date" name="start_date" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="bulk_end_date" class="form-label">End Date *</label>
                                <input type="date" class="form-control" id="bulk_end_date" name="end_date" required>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-3">
                        <label for="bulk_availability_type" class="form-label">Action *</label>
                        <select class="form-select" id="bulk_availability_type" name="availability_type" required>
                            <option value="available">Mark as Available</option>
                            <option value="blocked">Block Dates</option>
                            <option value="maintenance">Mark for Maintenance</option>
                        </select>
                    </div>
                    
                    <div class="mb-3">
                        <label for="bulk_price_override" class="form-label">Price Override (UGX)</label>
                        <input type="number" class="form-control" id="bulk_price_override" name="price_override" min="0" step="1000">
                        <div class="form-text">Leave empty to use default room price</div>
                    </div>
                    
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        <strong>Warning:</strong> This will update all selected dates. Existing bookings will not be affected.
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Bulk Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Booking Details Modal -->
<div class="modal fade" id="bookingDetailsModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Booking Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="bookingDetailsContent">
                <!-- Content will be loaded dynamically -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <div id="bookingActions">
                    <!-- Actions will be loaded dynamically -->
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.calendar-container {
    padding: 20px;
}

.calendar {
    width: 100%;
    border-collapse: collapse;
}

.calendar th,
.calendar td {
    border: 1px solid #dee2e6;
    padding: 8px;
    text-align: center;
    vertical-align: top;
    height: 100px;
    position: relative;
}

.calendar th {
    background-color: #f8f9fa;
    font-weight: 600;
}

.calendar .day-number {
    font-weight: 600;
    margin-bottom: 5px;
}

.calendar .booking-item {
    font-size: 0.75rem;
    padding: 2px 4px;
    margin: 1px 0;
    border-radius: 3px;
    cursor: pointer;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.calendar .booking-item.available {
    background-color: #d4edda;
    color: #155724;
}

.calendar .booking-item.partial {
    background-color: #fff3cd;
    color: #856404;
}

.calendar .booking-item.booked {
    background-color: #f8d7da;
    color: #721c24;
}

.calendar .booking-item.blocked {
    background-color: #e2e3e5;
    color: #383d41;
}

.calendar .booking-item.maintenance {
    background-color: #cce5ff;
    color: #004085;
}

.calendar .other-month {
    background-color: #f8f9fa;
    color: #6c757d;
}

.calendar .today {
    background-color: #e3f2fd;
}

.legend-color {
    border: 1px solid #dee2e6;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    let currentDate = new Date();
    let currentMonth = currentDate.getMonth();
    let currentYear = currentDate.getFullYear();
    
    // Initialize calendar
    generateCalendar(currentYear, currentMonth);
    
    // Event listeners
    document.getElementById('prevMonth').addEventListener('click', function() {
        currentMonth--;
        if (currentMonth < 0) {
            currentMonth = 11;
            currentYear--;
        }
        generateCalendar(currentYear, currentMonth);
    });
    
    document.getElementById('nextMonth').addEventListener('click', function() {
        currentMonth++;
        if (currentMonth > 11) {
            currentMonth = 0;
            currentYear++;
        }
        generateCalendar(currentYear, currentMonth);
    });
    
    // Hotel filter change
    document.getElementById('hotelFilter').addEventListener('change', function() {
        const selectedHotel = this.value;
        const roomFilter = document.getElementById('roomFilter');
        
        // Filter rooms based on selected hotel
        Array.from(roomFilter.options).forEach(option => {
            if (option.value === '') {
                option.style.display = 'block';
            } else {
                const hotelId = option.getAttribute('data-hotel');
                option.style.display = (hotelId === selectedHotel || selectedHotel === '') ? 'block' : 'none';
            }
        });
        
        // Reset room filter if hotel changed
        if (roomFilter.value && selectedHotel !== '') {
            const selectedRoomHotel = roomFilter.options[roomFilter.selectedIndex].getAttribute('data-hotel');
            if (selectedRoomHotel !== selectedHotel) {
                roomFilter.value = '';
            }
        }
        
        generateCalendar(currentYear, currentMonth);
    });
    
    // Room filter change
    document.getElementById('roomFilter').addEventListener('change', function() {
        generateCalendar(currentYear, currentMonth);
    });
    
    // Hotel selection in modals
    document.getElementById('hotel_id').addEventListener('change', function() {
        updateRoomOptions(this.value, 'room_id');
    });
    
    document.getElementById('bulk_hotel_id').addEventListener('change', function() {
        updateRoomOptions(this.value, 'bulk_room_id');
    });
    
    function updateRoomOptions(hotelId, selectId) {
        const roomSelect = document.getElementById(selectId);
        roomSelect.innerHTML = '<option value="">All Rooms</option>';
        
        if (hotelId) {
            // Filter rooms for selected hotel
            Array.from(document.getElementById('roomFilter').options).forEach(option => {
                if (option.value && option.getAttribute('data-hotel') === hotelId) {
                    const newOption = document.createElement('option');
                    newOption.value = option.value;
                    newOption.textContent = option.textContent.split(' - ')[0]; // Remove hotel name
                    roomSelect.appendChild(newOption);
                }
            });
        }
    }
    
    function generateCalendar(year, month) {
        const monthNames = [
            'January', 'February', 'March', 'April', 'May', 'June',
            'July', 'August', 'September', 'October', 'November', 'December'
        ];
        
        document.getElementById('currentMonth').textContent = monthNames[month] + ' ' + year;
        
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const startDate = new Date(firstDay);
        startDate.setDate(startDate.getDate() - firstDay.getDay());
        
        const calendar = document.getElementById('calendar');
        calendar.innerHTML = generateCalendarHTML(startDate, year, month);
        
        // Load bookings for the month
        loadBookingsForMonth(year, month);
    }
    
    function generateCalendarHTML(startDate, year, month) {
        const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        let html = '<table class="calendar"><thead><tr>';
        
        days.forEach(day => {
            html += `<th>${day}</th>`;
        });
        
        html += '</tr></thead><tbody>';
        
        const currentDate = new Date(startDate);
        for (let week = 0; week < 6; week++) {
            html += '<tr>';
            for (let day = 0; day < 7; day++) {
                const isCurrentMonth = currentDate.getMonth() === month;
                const isToday = currentDate.toDateString() === new Date().toDateString();
                const dayClass = !isCurrentMonth ? 'other-month' : (isToday ? 'today' : '');
                
                html += `<td class="${dayClass}" data-date="${currentDate.toISOString().split('T')[0]}">`;
                html += `<div class="day-number">${currentDate.getDate()}</div>`;
                html += '<div class="bookings-container"></div>';
                html += '</td>';
                
                currentDate.setDate(currentDate.getDate() + 1);
            }
            html += '</tr>';
        }
        
        html += '</tbody></table>';
        return html;
    }
    
    function loadBookingsForMonth(year, month) {
        const hotelId = document.getElementById('hotelFilter').value;
        const roomId = document.getElementById('roomFilter').value;
        
        // Simulate loading bookings (replace with actual API call)
        const bookings = <?= json_encode($bookings ?? []) ?>;
        
        bookings.forEach(booking => {
            const date = booking.date;
            const cell = document.querySelector(`[data-date="${date}"]`);
            if (cell) {
                const bookingsContainer = cell.querySelector('.bookings-container');
                const bookingItem = document.createElement('div');
                bookingItem.className = `booking-item ${booking.status}`;
                bookingItem.textContent = booking.title;
                bookingItem.onclick = () => showBookingDetails(booking.id);
                bookingsContainer.appendChild(bookingItem);
            }
        });
    }
    
    function showBookingDetails(bookingId) {
        // Load booking details via AJAX
        fetch(`/host/calendar/booking/${bookingId}`)
            .then(response => response.json())
            .then(data => {
                document.getElementById('bookingDetailsContent').innerHTML = data.html;
                document.getElementById('bookingActions').innerHTML = data.actions;
                new bootstrap.Modal(document.getElementById('bookingDetailsModal')).show();
            })
            .catch(error => {
                console.error('Error loading booking details:', error);
            });
    }
    
    // Form validation
    document.getElementById('addAvailabilityForm').addEventListener('submit', function(e) {
        const startDate = new Date(document.getElementById('start_date').value);
        const endDate = new Date(document.getElementById('end_date').value);
        
        if (endDate <= startDate) {
            e.preventDefault();
            alert('End date must be after start date!');
            return false;
        }
    });
    
    document.getElementById('bulkUpdateForm').addEventListener('submit', function(e) {
        const startDate = new Date(document.getElementById('bulk_start_date').value);
        const endDate = new Date(document.getElementById('bulk_end_date').value);
        
        if (endDate <= startDate) {
            e.preventDefault();
            alert('End date must be after start date!');
            return false;
        }
        
        if (!confirm('Are you sure you want to perform this bulk update? This action cannot be undone.')) {
            e.preventDefault();
            return false;
        }
    });
});
</script>
